esphome:
  name: $name
  friendly_name: $friendly_name
  name_add_mac_suffix: False
  project:
    name: "seeedstudio.mr60bha2_kit"
    version: "2025-02-26-15:08"
  platformio_options:
    board_upload.maximum_size: 4194304

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB # upload.flash_size
  framework:
    type: esp-idf
    version: latest

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

debug:
  update_interval: 5s

# Enable Home Assistant API
api:
  encryption:
    key: $api_encryption_key
ota:
  - platform: esphome
    password: $ota_password

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $name
    password: !secret wifi_password
  #use_address: $static_ip
  #https://esphome.io/components/wifi.html#wifi-power-save-mode
  power_save_mode: light
  enable_btm: True
  enable_rrm: True
  networks:
  - ssid: !secret wifi_office_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_bedroom_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_dining_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_entry_ssid
    password: !secret wifi_password
  
captive_portal:

#Ensure that we are not using the native component, it's flaky
seeed_mr60bha2: !remove
#Rather, use the external one from seeed
external_components:
  - source:
      type: git
      url: https://github.com/limengdu/MR60BHA2_ESPHome_external_components
      ref: main
    components: [ seeed_mr60bha2 ]
    refresh: 1min

# For XIAO ESP32C6 Onboard LED
# light:
#   - platform: status_led
#     name: "Switch state"
#     pin: GPIO15

light:
  - platform: esp32_rmt_led_strip
    id: led_ring
    name: "Front LED"
    pin: GPIO1
    num_leds: 1
    rgb_order: GRB
    chipset: ws2812
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 2s
      - pulse:
          name: "Asymmetrical Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
      - lambda:
          name: "Distance Visualization"
          update_interval: 1s
          lambda: |-
            float distance_var = id(distance).state;
            float brightness = (distance_var / 20.0) * 89.0 + 11.0; // Map distance 0-20 to brightness 11-100
            int red = (int)(255 * (1 - (distance_var / 20.0))); // Red decreases as distance increases
            int green = (int)(255 * (distance_var / 20.0)); // Green increases as distance increases
            int blue = (int)(255 * (distance_var / 20.0)); // Blue increases as distance increases
            auto call = id(led_ring).turn_on();
            call.set_brightness(brightness / 100.0);
            call.set_rgb(red / 255.0, green / 255.0, blue / 255.0);
            call.perform();



i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1

seeed_mr60bha2:
  id: my_seeed_mr60bha2

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Person Detected (Raw)"
      id: person_detected_raw
      device_class: occupancy
      entity_category: "diagnostic"

  - platform: template
    id: person_detected
    name: "Person Detected"
    device_class: occupancy
    lambda: |-
      return id(person_detected_raw).state;
    filters:
      - delayed_off: 60s
    
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    unit_of_measurement: "dB"
    update_interval: 60s
    entity_category: "diagnostic"
    internal: false

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: signal_strength
    state_class: measurement

  - platform: uptime
    name: Uptime
    entity_category: "diagnostic"

  - platform: bh1750
    name: "Ambient Light"
    address: 0x23
    update_interval: 1s
    accuracy_decimals: 0
    device_class: illuminance
    id: illuminance
    state_class: measurement
    filters:
      - or:
          - delta: 10
          - exponential_moving_average:
              #Closer to 1.0: Less smoothing, more responsive to recent changes. The output will more closely follow the raw sensor data.
              #Closer to 0.0: More smoothing, less responsive to recent changes. The output will be more stable, but changes will be reflected more slowly.
              alpha: 0.2  # Adjust alpha value (0.0 - 1.0)
              send_every: 15
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Respiratory Rate"
      id: respiratory_rate
      state_class: measurement
      # filters:
      #   - or:
      #     - delta: 2
      #     - exponential_moving_average: 
      #         alpha: .2
      #         send_every: 5
    heart_rate:
      name: "Heart Rate"
      id: heart_rate
      state_class: measurement
      # filters:
      #   - or:
      #     - delta: 3
      #     - exponential_moving_average: 
      #         alpha: .2
      #         send_every: 5
    distance:
      name: "Distance"
      id: distance
      unit_of_measurement: ft
      accuracy_decimals: 1
      filters:
        - multiply: .0328084 # Convert centimeters to feet
        # - or:
        #   - delta: 1
        #   - exponential_moving_average: 
        #       alpha: .2
        #       send_every: 5
    num_targets:
      name: "Number of Targets"
      id: number_of_targets
      unit_of_measurement: "People"
      state_class: measurement
      accuracy_decimals: 0
      # filters:
      # - delta: 1

  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      address_0:
        name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"


